trigger:
- master

# variables
variables:
  tag:  '$(Build.BuildId)'

stage:
# Build Stage
- stage: Build
  displayName:  Build Stage
  jobs:
  - job:  Build
    displayName:  Build Job
    pool: 
      vmImage:  'ubuntu-latest'
    steps:  
    # Build Docker image and push to ACR
    - task: Docker@2
      inputs:
        containerRegistry: 'acr-falco-test'
        repository: 'custom2aksnginxapp1'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
          $(Build.SourceVersion)

    # copy Artifact
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)/kube-manifest'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
        OverWrite: true

   # Publish Artifact
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'kube manifest'
        publishLocation: 'Container'
